name: example-conditional
on: [push]
jobs:
    hello-world:
        if: github.repository == 'jhosmanB/p-ghActions'
        runs-on: ubuntu-latest
        steps:
          - name: hello-world
            run: echo "Hello, World!"
    goodby-moon:
        runs-on: ubuntu-latest
        steps:
          - name: goodbye-moon
            run: echo "Goodbye, Moon!"
