on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
jobs:
    hello-world:
        runs-on: ubuntu-lastest
        steps:
            - name: "Echo basic information"
              run: |
                echo "REF: $GITHUB_REF"
                echo "job ID: $GITHUB_JOB"
                echo "Action: $GITHUB_ACTION"
                echo "Actor: $GITHUB_ACTOR"
