name: Scheduled Hello World
on:
    schedule:
        - cron: "*/2 * * * *"

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: print time
              run: echo "The current server time is $(date)"