name: "Workflow commands"
on: [push]
jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: "group logging"
              run: |
                echo "::group::My group"
                echo "This is a message inside the group"
                echo "msg2 inside the group"
                echo "::endgroup::"
            - name: "set output"
              run: |
                echo "MY_OUTPUT=Hello World" >> $GITHUB_ENV
            - name: "use output"
              run: |
                echo "The output is $MY_OUTPUT"